#!/bin/bash
curl -s -o ~/Pictures/fatcat.jpg 'https://glaminlalaland.files.wordpress.com/2012/11/fattest-cat1.jpg' 

osascript -e "tell application \"System Events\"
    set desktopCount to count of desktops
    repeat with desktopNumber from 1 to desktopCount
        tell desktop desktopNumber
            set picture to \"/Users/$USER/Pictures/fatcat.jpg\"
        end tell
    end repeat
end tell"
